---
title: "HuYuDataInsight LLC"
author: "Zhaowei Cai"
date: "2024-05-14"
output: pdf_document
---

**Q3**

(a)
```{r}
library(quantmod)
library(urca)
library(forecast)
library(tseries)
library(fGarch)
library(zoo)
library(tseries)
library(rugarch) 

data = read.csv('TSLA2.csv')

closing = data$Close # closing price
log_closing = log(data$Close) # log closing price
log_return = na.omit(diff(log(data$Close))) # log return
time = as.Date(data$Date, format = '%m/%d/%y')

##Check for the trend (the Augmented Dickey–Fuller (ADF) test)
summary(ur.df(log_return, type='trend', lags=20, selectlags="BIC"))
# From the result, we can see that there is no drift. 
# Also, there is no linear trend for this time series because the coefficient for tt is not significant.


##Check for the seasonality
n = length(log_return)
acf(log_return,main="ACF of the log return",yaxt="n")
ci=qnorm(c(0.025, 0.975))/sqrt(n)
text(y=ci,par("usr")[1],labels=round(ci,4),pos=2,xpd=TRUE)
pacf(log_return,main="PACF of the log return",yaxt="n")
text(y=ci,par("usr")[1],labels=round(ci,4),pos=2,xpd=TRUE)
spec.pgram(log_return,main="Series: the log return")
# we cannot find any evidence for seasonality. 

# also
adf.test(log_return)
# The data is stationary. Difference is not needed.
```

(b)
```{r}
# There is no drift or time trend
fit = auto.arima(log_return, max.p=25, max.q=25, ic="bic",
                       seasonal=F, lambda=NULL, 
                       stepwise=FALSE, approximation=FALSE
                       )
summary(fit)
# ARMA(0,0)
tsdiag(fit)
shapiro.test(fit$residuals)
# The null-hypothesis of this test is that the population is normally distributed. 
# The null hypothesis is rejected and there is evidence that the residuals tested are not normally distributed. 
```

(c)
```{r}
prediction <- forecast(fit, h=1, level=0.95) # one-day ahead log return
last_close_price <- closing[length(closing)]
(lower_interval <-as.numeric(last_close_price*exp(prediction$lower)))
(price_forecast <-as.numeric(last_close_price*exp(prediction$mean)))
(upper_interval <-as.numeric(last_close_price*exp(prediction$upper)))


# Print the forecasted closing price and prediction interval
cat("1-day ahead closing price forecast:", price_forecast, "\n")
cat("95% Prediction Interval: (", lower_interval, ", ", upper_interval, ")\n")
```

(d)
```{r}
# Fit the mean model first
arma_model <- auto.arima(log_return)
arma_model
garch_spec <- ugarchspec(variance.model = list(model = "sGARCH", garchOrder = c(1,1)),
                         mean.model = list(armaOrder = c(0,0)))
garch_fit <- ugarchfit(spec = garch_spec, data = arma_model$residuals)
garch_fit

forecasted_returns <- ugarchforecast(garch_fit, n.ahead = 1)
last_close_price <- closing[length(closing)]
(price_forecast <-as.numeric(last_close_price*exp(forecasted_returns@forecast$seriesFor)))
(lower_interval <- as.numeric(price_forecast*exp(qnorm(0.025)*forecasted_returns@forecast$sigmaFor)))
(upper_interval <- as.numeric(price_forecast*exp(qnorm(0.975)*forecasted_returns@forecast$sigmaFor)))

# Print the forecasted closing price and prediction interval
cat("1-day ahead closing price forecast:", price_forecast, "\n")
cat("95% Prediction Interval: (", lower_interval, ", ", upper_interval, ")\n")
```